//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookGenre
    {
        public int Id { get; set; }
        public Nullable<int> IdBook { get; set; }
        public Nullable<int> IdGenre { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Genre Genre { get; set; }
    }
}
