//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BorrowedBookOverview
    {
        public int Id { get; set; }
        public Nullable<int> IdLibraryMember { get; set; }
        public Nullable<int> IdState { get; set; }
        public Nullable<System.DateTime> BorrowDate { get; set; }
        public Nullable<System.DateTime> ReturnDate { get; set; }
        public Nullable<int> IdBookCopy { get; set; }
    
        public virtual BookCopy BookCopy { get; set; }
        public virtual BorrowedBookState BorrowedBookState { get; set; }
        public virtual LibraryMember LibraryMember { get; set; }
    }
}
